feat: generic run-consul-terraform-sync script
Closes ESC-355

diff --git a/files/run-consul-terraform-sync b/files/run-consul-terraform-sync
--- a/files/run-consul-terraform-sync
+++ b/files/run-consul-terraform-sync
@@ -14,6 +14,81 @@ SCRIPT_NAME="$(basename "$0")"
 
 NAME="consul-terraform-sync"
 
+declare -gA VARIABLES
+
+function remove_surrounding_quotes() {
+  local input_str="$1"
+
+  if [[ $input_str == \"*\" && $input_str == *\" ]]; then
+    # Remove double quotes from both ends
+    input_str="${input_str%\"}"
+    input_str="${input_str#\"}"
+  elif [[ $input_str == \'*\' && $input_str == *\' ]]; then
+    # Remove single quotes from both ends
+    input_str="${input_str%\'}"
+    input_str="${input_str#\'}"
+  fi
+
+  echo "$input_str"
+}
+
+function read_env_from_string() {
+  local input_str="$1"
+  local IFS='='
+  read -ra parts <<<"$input_str"
+
+  # Check if the string contains exactly one equal sign
+  if [ "${#parts[@]}" -ne 2 ]; then
+    echo "Error: The string must contain exactly one equal sign."
+    return 1
+  fi
+
+  local key="${parts[0]}"
+  local value="${parts[1]}"
+
+  if [[ ! $key =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
+    return 1
+  fi
+
+  value="${value%%' '}" # Del trailing spaces
+  value="${value##' '}" # Del leading spaces
+
+  VARIABLES["${key}"]="$(remove_surrounding_quotes "${value}")"
+}
+
+function read_env_from_file() {
+  local env_file="$1"
+
+  while IFS='=' read -r key value; do
+    # Skip lines that do not look like assignments
+    [[ $key =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]] || continue
+
+    value="${value%%#*}"  # Del everything after #
+    value="${value%%' '}" # Del trailing spaces
+    value="${value##' '}" # Del leading spaces
+
+    # Assign to the array
+    VARIABLES["$key"]="$(remove_surrounding_quotes "${value}")"
+  done <"$env_file"
+}
+
+function array_to_json() {
+  declare -n arr=$1
+  local json_str=""
+
+  for key in "${!arr[@]}"; do
+    value="${arr[$key]}"
+    # Escape double quotes in the value
+    value="${value//\"/\\\"}"
+    json_str+="\"$key\":\"$value\","
+  done
+
+  # Remove the trailing comma and wrap in braces
+  json_str="{${json_str%,}}"
+
+  echo "$json_str" | jq .
+}
+
 function wrap() {
   local strings="${1}"
 
@@ -79,6 +154,7 @@ function print_usage() {
     echo -e "--module-alb-enabled|Enable ALB module."
     echo -e "--module-alb-version|escapace/alb-nia/aws Terraform module version."
     echo -e "--module-alb-listener-arn|ARN of the Application Load Balancer Listener."
+    echo -e "--module-alb-services-overrides|JSON encoded services overrides variables."
     echo -e "--module-dns-enabled|Enable DNS module."
     echo -e "--module-dns-version|escapace/route53-nia/aws Terraform module version."
     echo -e "--module-dns-zone-id|Route53 hosted zone id."
@@ -207,63 +283,6 @@ function start_consul_terraform_sync() {
   sudo systemctl --no-block restart ferm ${NAME}.service
 }
 
-function module_alb_configuration() {
-  local -r config_dir="${1}"
-  local -r variables_dir="${2}"
-  local -r module_version="${3}"
-  local -r listener_arn="${4}"
-
-  local -r config_path="${config_dir}/alb.hcl"
-  local -r variables_path="${variables_dir}/alb.tfvars"
-
-  #
-  # ALB Variables
-  #
-
-  log_info "Writing ${variables_path}"
-
-  local -r variables=$(
-    cat <<EOF
-region="${EC2_INSTANCE_REGION}"
-vpc_id="${EC2_INSTANCE_ETH0_VPC_ID}"
-listener_arn="${listener_arn}"
-EOF
-  )
-
-  echo -e "${variables}" >"${variables_path}"
-
-  chown ${NAME}:${NAME} "${variables_path}"
-  chmod 640 "${variables_path}"
-
-  #
-  # ALB Configuration
-  #
-
-  log_info "Writing ${config_path}"
-
-  local -r config=$(
-    cat <<EOF
-task {
-  name        = "alb"
-  description = "Application Load Balancer"
-  module      = "escapace/alb-nia/aws"
-  version     = "${module_version}"
-
-  variable_files = ["${variables_path}"]
-
-  condition "services" {
-    regexp = ".*"
-  }
-}
-EOF
-  )
-
-  echo -e "${config}" >"${config_path}"
-
-  chown ${NAME}:${NAME} "${config_path}"
-  chmod 640 "${config_path}"
-}
-
 function write_ferm_configuration() {
   log_info "Writing ferm configuration"
 
@@ -302,62 +321,6 @@ EOF
   chmod 600 "${template_path}"
 }
 
-function module_dns_configuration() {
-  local -r config_dir="${1}"
-  local -r variables_dir="${2}"
-  local -r module_version="${3}"
-  local -r zone_id="${4}"
-
-  local -r config_path="${config_dir}/dns.hcl"
-  local -r variables_path="${variables_dir}/dns.tfvars"
-
-  #
-  # DNS Variables
-  #
-
-  log_info "Writing ${variables_path}"
-
-  local -r variables=$(
-    cat <<EOF
-region="${EC2_INSTANCE_REGION}"
-zone_id="${zone_id}"
-EOF
-  )
-
-  echo -e "${variables}" >"${variables_path}"
-
-  chown ${NAME}:${NAME} "${variables_path}"
-  chmod 640 "${variables_path}"
-
-  #
-  # DNS Configuration
-  #
-
-  log_info "Writing ${config_path}"
-
-  local -r config=$(
-    cat <<EOF
-task {
-  name        = "dns"
-  description = "Route53"
-  module      = "escapace/route53-nia/aws"
-  version     = "${module_version}"
-
-  variable_files = ["${variables_path}"]
-
-  condition "services" {
-    regexp = ".*"
-  }
-}
-EOF
-  )
-
-  echo -e "${config}" >"${config_path}"
-
-  chown ${NAME}:${NAME} "${config_path}"
-  chmod 640 "${config_path}"
-}
-
 function trust-ca() {
   local -r source="${1}"
   local name
@@ -371,6 +334,16 @@ function trust-ca() {
   chmod 644 "${path}"
 
   update-ca-trust
+}
+
+function render_template() {
+  local secrets_bucket_name="${1}"
+  local role="${2}"
+  local template="${3}"
+
+  array_to_json "VARIABLES" | gomplate \
+    -i "$(get_object_value "${secrets_bucket_name}" "${role}/${NAME}/${NAME}-template-${3}")" \
+    -d data=stdin:///data.json
 }
 
 function run() {
@@ -391,14 +364,9 @@ function run() {
   local secrets_bucket_name=""
   local terraform_version="1.6.2"
   local log_level="ERR"
+  local tasks=()
 
-  local module_alb_enabled="false"
-  local module_alb_version=""
-  local module_alb_listener_arn=""
-
-  local module_dns_enabled="false"
-  local module_dns_version=""
-  local module_dns_zone_id=""
+  read_env_from_file "/etc/sysconfig/ec2-environment"
 
   while [[ $# -gt 0 ]]; do
     local key="$1"
@@ -407,6 +375,11 @@ function run() {
     --role)
       assert_not_empty "$key" "$2"
       role="$2"
+      shift
+      ;;
+    --task)
+      assert_not_empty "$key" "$2"
+      tasks+=("${2}")
       shift
       ;;
     --secrets-bucket-name)
@@ -424,30 +397,9 @@ function run() {
       log_level="$2"
       shift
       ;;
-    --module-alb-enabled)
-      module_alb_enabled="true"
-      ;;
-    --module-alb-version)
+    --variable)
       assert_not_empty "$key" "$2"
-      module_alb_version="$2"
-      shift
-      ;;
-    --module-alb-listener-arn)
-      assert_not_empty "$key" "$2"
-      module_alb_listener_arn="$2"
-      shift
-      ;;
-    --module-dns-enabled)
-      module_dns_enabled="true"
-      ;;
-    --module-dns-version)
-      assert_not_empty "$key" "$2"
-      module_dns_version="$2"
-      shift
-      ;;
-    --module-dns-zone-id)
-      assert_not_empty "$key" "$2"
-      module_dns_zone_id="$2"
+      read_env_from_string "${2}"
       shift
       ;;
     --help)
@@ -470,25 +422,6 @@ function run() {
 
   assert_is_installed "update-ca-trust"
   assert_not_empty "--secrets-bucket-name" "$secrets_bucket_name"
-
-  if [[ "${module_alb_enabled}" == "true" ]]; then
-    assert_not_empty "--module-alb-listener-arn" "$module_alb_listener_arn"
-    assert_not_empty "--module-alb-version" "$module_alb_version"
-  fi
-
-  if [[ "${module_dns_enabled}" == "true" ]]; then
-    assert_not_empty "--module-dns-zone-id" "$module_dns_enabled"
-    assert_not_empty "--module-dns-version" "$module_dns_version"
-  fi
-
-  if [[ "${module_alb_enabled}" == "false" && "${module_dns_enabled}" == "false" ]]; then
-    log_error "Enable at least one module."
-
-    exit 1
-  fi
-
-  # else
-  # fi
 
   if ! [[ "$role" == "server" || "$role" == "client" || "$role" == "bastion" ]]; then
     log_error "Unrecognized value for the --role flag."
@@ -719,21 +652,31 @@ EOF
   chown ${NAME}:${NAME} "${config_path}"
   chmod 640 "${config_path}"
 
-  if [[ "${module_alb_enabled}" == "true" ]]; then
-    module_alb_configuration \
-      "${config_dir}" \
-      "${variables_dir}" \
-      "${module_alb_version}" \
-      "${module_alb_listener_arn}"
-  fi
+  #
+  # Tasks
+  #
 
-  if [[ "${module_dns_enabled}" == "true" ]]; then
-    module_dns_configuration \
-      "${config_dir}" \
-      "${variables_dir}" \
-      "${module_dns_version}" \
-      "${module_dns_zone_id}"
-  fi
+  for task in "${tasks[@]}"; do
+    local task_config_path="${config_dir}/${task}.hcl"
+    local task_tfvars_path="${variables_dir}/${task}.tfvars"
+
+    render_template \
+      "${secrets_bucket_name}" \
+      "${role}" \
+      "${task}-config" >"${task_config_path}"
+
+    chown ${NAME}:${NAME} "${task_config_path}"
+    chmod 640 "${task_config_path}"
+
+    if render_template \
+      "${secrets_bucket_name}" \
+      "${role}" \
+      "${task}-tfvars" >"${task_tfvars_path}"; then
+
+      chown ${NAME}:${NAME} "${task_tfvars_path}"
+      chmod 640 "${task_tfvars_path}"
+    fi
+  done
 
   # write_ferm_configuration \
   #   "false" \
