feat: trust-ca

diff --git a/files/run-consul b/files/run-consul
--- a/files/run-consul
+++ b/files/run-consul
@@ -13,15 +13,11 @@ SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 SCRIPT_NAME="$(basename "$0")"
 
 readonly AWS_ASG_TAG_KEY="aws:autoscaling:groupName"
-
 readonly CONSUL_CONFIG_FILE="default.json"
-
 readonly CONSUL_SYSTEMD_CONFIG_PATH="/usr/lib/systemd/system/consul.service"
 readonly CONSUL_BOOTSTRAP_SYSTEMD_CONFIG_PATH="/etc/systemd/system/consul-bootstrap.service.d/010-secrets-bucket.conf"
-
 readonly MAX_RETRIES=30
 readonly SLEEP_BETWEEN_RETRIES_SEC=10
-
 readonly DEFAULT_AUTOPILOT_CLEANUP_DEAD_SERVERS="true"
 readonly DEFAULT_AUTOPILOT_LAST_CONTACT_THRESHOLD="200ms"
 readonly DEFAULT_AUTOPILOT_MAX_TRAILING_LOGS="250"
@@ -29,54 +25,104 @@ readonly DEFAULT_AUTOPILOT_SERVER_STABILIZATION_TIME="10s"
 readonly DEFAULT_AUTOPILOT_REDUNDANCY_ZONE_TAG="az"
 readonly DEFAULT_AUTOPILOT_DISABLE_UPGRADE_MIGRATION="false"
 
-set -o allexport
-source "/etc/sysconfig/ec2-environment"
-set +o allexport
+function wrap {
+ local strings="${1}"
+
+ local length
+ local cols
+ local width
+
+ length="$(echo -n "${strings}" | awk -F '|' '{print $1}' | awk '{ print length }' | sort -n | tail -1)"
+ cols="$(tput cols)"
+
+ if [[ $(( (cols - 4) / length )) -ge 2 ]]
+ then
+  if [[ $((cols - length - 4)) -ge 80 ]]
+  then
+    width=80
+  else
+    width=$((cols - length - 4))
+  fi
+
+   echo -e "${strings}" | \
+    fold -s -w "${width}" | \
+    sed -e "/--/! s|^| \||g" | \
+    column -t -s '|' | \
+    sed  's/^/  /'
+ else
+    local lines
+    local line
+    readarray -t lines <<< "${strings}"
+    local option
+    local description
+
+    if [[ "${cols}" -ge 80 ]]
+    then
+      width="78"
+    else
+      width=$((cols - 2))
+    fi
+
+    for line in "${lines[@]}"; do
+      option="${line%%|*}"
+      description=${line#*|}
+
+      echo "${option}"
+      echo
+      echo "${description}" | fold -s -w "${width}" |  sed  's/^/  /'
+      echo
+    done
+ fi
+}
 
 function print_usage {
   echo
-  echo "Usage: run-consul [OPTIONS]"
+  echo "Usage: $SCRIPT_NAME [OPTIONS]"
   echo
   echo "This script is used to configure and run Consul on an AWS server."
   echo
   echo "Options:"
   echo
-  echo -e "  --server\t\tIf set, run in server mode. Optional. Exactly one of --server or --client must be set."
-  echo -e "  --client\t\tIf set, run in client mode. Optional. Exactly one of --server or --client must be set."
-  echo -e "  --cluster-tag-key\tAutomatically form a cluster with Instances that have this tag key and the tag value in --cluster-tag-value. Optional."
-  echo -e "  --cluster-tag-value\tAutomatically form a cluster with Instances that have the tag key in --cluster-tag-key and this tag value. Optional."
-  echo -e "  --region\t\tThe name of the region Consul is running in. Optional. If not specified, will default to AWS region name."
-  echo -e "  --config-dir\t\tThe path to the Consul config folder. Optional. Default is the absolute path of '../config', relative to this script."
-  echo -e "  --data-dir\t\tThe path to the Consul data folder. Optional. Default is the absolute path of '../data', relative to this script."
-  echo -e "  --systemd-stdout\t\tThe StandardOutput option of the systemd unit.  Optional.  If not configured, uses systemd's default (journal)."
-  echo -e "  --systemd-stderr\t\tThe StandardError option of the systemd unit.  Optional.  If not configured, uses systemd's default (inherit)."
-  echo -e "  --bin-dir\t\tThe path to the folder with Consul binary. Optional. Default is the absolute path of the parent folder of this script."
-  echo -e "  --user\t\tThe user to run Consul as. Optional. Default is to use the owner of --config-dir."
-  echo -e "  --enable-gossip-encryption\t\tEnable encryption of gossip traffic between nodes. Optional. Must also specify --gossip-encryption-key."
-  echo -e "  --secrets-bucket-name\t\tAWS S3 secrets bucket name."
-  echo -e "  --enable-tls-encryption\t\tEnable encryption of traffic between nodes. Optional. Must also specify --ca-file-path, --cert-file-path and --key-file-path."
-  echo -e "  --verify-server-hostname\tWhen passed in, enable server hostname verification as part of RPC encryption. Each server in Consul should get their own certificate that contains SERVERNAME.REGION.consul in the hostname or SAN. This prevents an authenticated agent from being converted into a server that streams all data, bypassing ACLs."
-  echo -e "  --verify-incoming-https\tIf set to true, Consul requires that all incoming HTTPS connections make use of TLS."
-  echo -e "  --environment\t\tA single environment variable in the key/value pair form 'KEY=\"val\"' to pass to Consul as environment variable when starting it up. Repeat this option for additional variables. Optional."
-  echo -e "  --skip-consul-config\tIf this flag is set, don't generate a Consul configuration file. Optional. Default is false."
-  echo -e "  --ui\tEnables the service of the web UI from this agent. Optional."
-  echo -e "  --interface\tBind to interface. Optional."
-  echo -e "  --ipv6\tUse IPv6. Optional."
+
+  wrap "$(
+    echo -e "--server|If set, run in server mode."
+    echo -e "--client|If set, run in client mode."
+    echo -e "--auto-join-tag-key|Automatically form a cluster with instances that have this tag key."
+    echo -e "--auto-join-tag-value|Automatically form a cluster with instances that have this tag value."
+    echo -e "--config-dir|The path to the Consul config folder."
+    echo -e "--data-dir|The path to the Consul data folder."
+    echo -e "--systemd-stdout|The StandardOutput option of the systemd unit."
+    echo -e "--systemd-stderr|The StandardError option of the systemd unit."
+    echo -e "--bin-dir|The path to the folder with Consul binary."
+    echo -e "--user|The user to run Consul as. Optional."
+    echo -e "--enable-gossip-encryption|Enable encryption of gossip traffic between nodes."
+    echo -e "--secrets-bucket-name|AWS S3 secrets bucket name."
+    echo -e "--enable-tls-encryption|Enable encryption of traffic between nodes."
+    echo -e "--verify-server-hostname|When passed in, enable server hostname verification as part of RPC encryption."
+    echo -e "--verify-incoming-https|If set to true, Consul requires that all incoming HTTPS connections make use of TLS."
+    echo -e "--environment|A single environment variable in the key/value pair form 'KEY=\"val\"' to pass to Consul as environment variable when starting it up."
+    echo -e "--skip-consul-config|If this flag is set, don't generate a Consul configuration file."
+    echo -e "--ui|Enables the service of the web UI from this agent."
+    echo -e "--interface|Bind to interface."
+    echo -e "--ipv6|Use IPv6."
+  )"
   echo
   echo "Options for Consul Autopilot:"
   echo
-  echo -e "  --autopilot-cleanup-dead-servers\tSet to true or false to control the automatic removal of dead server nodes periodically and whenever a new server is added to the cluster. Defaults to $DEFAULT_AUTOPILOT_CLEANUP_DEAD_SERVERS. Optional."
-  echo -e "  --autopilot-last-contact-threshold\tControls the maximum amount of time a server can go without contact from the leader before being considered unhealthy. Must be a duration value such as 10s. Defaults to $DEFAULT_AUTOPILOT_LAST_CONTACT_THRESHOLD. Optional."
-  echo -e "  --autopilot-max-trailing-logs\t\tControls the maximum number of log entries that a server can trail the leader by before being considered unhealthy. Defaults to $DEFAULT_AUTOPILOT_MAX_TRAILING_LOGS. Optional."
-  echo -e "  --autopilot-server-stabilization-time\tControls the minimum amount of time a server must be stable in the 'healthy' state before being added to the cluster. Only takes effect if all servers are running Raft protocol version 3 or higher. Must be a duration value such as 30s. Defaults to $DEFAULT_AUTOPILOT_SERVER_STABILIZATION_TIME. Optional."
-  echo -e "  --autopilot-redundancy-zone-tag\t\t(Enterprise-only) This controls the -node-meta key to use when Autopilot is separating servers into zones for redundancy. Only one server in each zone can be a voting member at one time. If left blank, this feature will be disabled. Defaults to $DEFAULT_AUTOPILOT_REDUNDANCY_ZONE_TAG. Optional."
-  echo -e "  --autopilot-disable-upgrade-migration\t(Enterprise-only) If this flag is set, this will disable Autopilot's upgrade migration strategy in Consul Enterprise of waiting until enough newer-versioned servers have been added to the cluster before promoting any of them to voters. Defaults to $DEFAULT_AUTOPILOT_DISABLE_UPGRADE_MIGRATION. Optional."
-  echo -e "  --autopilot-upgrade-version-tag\t\t(Enterprise-only) That tag to be used to override the version information used during a migration. Optional."
-  echo
+  wrap "$(
+    echo -e "--autopilot-cleanup-dead-servers|Set to true or false to control the automatic removal of dead server nodes periodically and whenever a new server is added to the cluster. Defaults to $DEFAULT_AUTOPILOT_CLEANUP_DEAD_SERVERS. Optional."
+    echo -e "--autopilot-last-contact-threshold|Controls the maximum amount of time a server can go without contact from the leader before being considered unhealthy. Must be a duration value such as 10s. Defaults to $DEFAULT_AUTOPILOT_LAST_CONTACT_THRESHOLD. Optional."
+    echo -e "--autopilot-max-trailing-logs|Controls the maximum number of log entries that a server can trail the leader by before being considered unhealthy. Defaults to $DEFAULT_AUTOPILOT_MAX_TRAILING_LOGS. Optional."
+    echo -e "--autopilot-server-stabilization-time|Controls the minimum amount of time a server must be stable in the 'healthy' state before being added to the cluster. Only takes effect if all servers are running Raft protocol version 3 or higher. Must be a duration value such as 30s. Defaults to $DEFAULT_AUTOPILOT_SERVER_STABILIZATION_TIME. Optional."
+    echo -e "--autopilot-redundancy-zone-tag|(Enterprise-only) This controls the -node-meta key to use when Autopilot is separating servers into zones for redundancy. Only one server in each zone can be a voting member at one time. If left blank, this feature will be disabled. Defaults to $DEFAULT_AUTOPILOT_REDUNDANCY_ZONE_TAG. Optional."
+    echo -e "--autopilot-disable-upgrade-migration|(Enterprise-only) If this flag is set, this will disable Autopilot's upgrade migration strategy in Consul Enterprise of waiting until enough newer-versioned servers have been added to the cluster before promoting any of them to voters. Defaults to $DEFAULT_AUTOPILOT_DISABLE_UPGRADE_MIGRATION. Optional."
+    echo -e "--autopilot-upgrade-version-tag|(Enterprise-only) That tag to be used to override the version information used during a migration. Optional."
+  )"
   echo
   echo "Example:"
   echo
-  echo "  run-consul --server --config-dir /custom/path/to/consul/config"
+  echo "  $SCRIPT_NAME --server --config-dir /custom/path/to/consul/config"
+  echo
 }
 
 function log {
@@ -277,52 +323,37 @@ function get_vpc_cidr {
   echo "${!variable_reference}"
 }
 
-function get_prefix_cidr {
-  local -r ipv6="${1}"
-  local -r interface="${2}"
-
-  local type
-  local variable_reference
-
-  type="$(address_type "${ipv6}")"
-
-  variable_reference="EC2_INSTANCE_${interface^^}_${type^^}_PREFIX_CIDR"
-
-  echo "${!variable_reference}"
-}
-
 function generate_consul_config {
   umask 027
 
   local -r server="${1}"
   local -r config_dir="${2}"
   local -r user="${3}"
-  local -r cluster_tag_key="${4}"
-  local -r cluster_tag_value="${5}"
-  local -r region="${6}"
-  local -r enable_gossip_encryption="${7}"
-  local -r gossip_encryption_key="${8}"
-  local -r enable_tls_encryption="${9}"
-  local -r verify_server_hostname="${10}"
-  local -r verify_incoming_https="${11}"
-  local -r ca_file_path="${12}"
-  local -r cert_file_path="${13}"
-  local -r key_file_path="${14}"
-  local -r cleanup_dead_servers="${15}"
-  local -r last_contact_threshold="${16}"
-  local -r max_trailing_logs="${17}"
-  local -r server_stabilization_time="${18}"
-  local -r redundancy_zone_tag="${19}"
-  local -r disable_upgrade_migration="${20}"
-  local -r upgrade_version_tag=${21}
-  local -r ui_config_enabled=${22}
-  local -r acl_tokens_master="${23}"
-  local -r acl_tokens_agent="${24}"
-  local -r ipv6="${25}"
-  local -r interface="${26}"
+  local -r auto_join_tag_key="${4}"
+  local -r auto_join_tag_value="${5}"
+  local -r enable_gossip_encryption="${6}"
+  local -r gossip_encryption_key="${7}"
+  local -r enable_tls_encryption="${8}"
+  local -r verify_server_hostname="${9}"
+  local -r verify_incoming_https="${10}"
+  local -r ca_file_path="${11}"
+  local -r cert_file_path="${12}"
+  local -r key_file_path="${13}"
+  local -r cleanup_dead_servers="${14}"
+  local -r last_contact_threshold="${15}"
+  local -r max_trailing_logs="${16}"
+  local -r server_stabilization_time="${17}"
+  local -r redundancy_zone_tag="${18}"
+  local -r disable_upgrade_migration="${19}"
+  local -r upgrade_version_tag=${20}
+  local -r ui_config_enabled=${21}
+  local -r acl_tokens_master="${22}"
+  local -r acl_tokens_agent="${23}"
+  local -r ipv6="${24}"
+  local -r interface="${25}"
   local -r config_path="$config_dir/$CONSUL_CONFIG_FILE"
 
-  shift 26
+  shift 25
 
   local advertise_addr
   local bind_addr
@@ -338,19 +369,19 @@ function generate_consul_config {
   # hostname="$(get_instance_hostname)"
 
   local retry_join_json=""
-  if [[ -z "$cluster_tag_key" || -z "$cluster_tag_value" ]]; then
-    log_warn "Either the cluster tag key ($cluster_tag_key) or value ($cluster_tag_value) is empty. Will not automatically try to form a cluster based on EC2 tags."
+  if [[ -z "$auto_join_tag_key" || -z "$auto_join_tag_value" ]]; then
+    log_warn "Either the cluster tag key ($auto_join_tag_key) or value ($auto_join_tag_value) is empty. Will not automatically try to form a cluster based on EC2 tags."
   else
 
     if [[ "$ipv6" == "false" ]]
     then
       retry_join_json=$(cat <<EOF
-"retry_join": ["provider=aws addr_type=private_v4 region=$instance_region tag_key=$cluster_tag_key tag_value=$cluster_tag_value"],
+"retry_join": ["provider=aws addr_type=private_v4 region=$instance_region tag_key=$auto_join_tag_key tag_value=$auto_join_tag_value"],
 EOF
 )
     else
       retry_join_json=$(cat <<EOF
-"retry_join": ["provider=aws addr_type=public_v6 region=$instance_region tag_key=$cluster_tag_key tag_value=$cluster_tag_value"],
+"retry_join": ["provider=aws addr_type=public_v6 region=$instance_region tag_key=$auto_join_tag_key tag_value=$auto_join_tag_value"],
 EOF
 )
     fi
@@ -464,7 +495,7 @@ EOF
     "https": 8501,
     "grpc": 8502
   },
-  "datacenter": "$region",
+  "datacenter": "$instance_region",
   "node_name": "$instance_id",
   $retry_join_json
   "server": $server,
@@ -583,7 +614,6 @@ function generate_ferm_config {
 
   local address
   local domain
-  local prefix_cidr=""
   local vpc_cidr
 
   if [[ "$ipv6" == "true"  ]]
@@ -595,11 +625,6 @@ function generate_ferm_config {
 
   address="$(get_consul_address "${server}" "${ipv6}" "${interface}")"
   vpc_cidr="$(get_vpc_cidr "${ipv6}" "${interface}")"
-
-  if [[ "$server" == "false"  ]]
-  then
-    prefix_cidr="$(get_prefix_cidr "${ipv6}" "${interface}")"
-  fi
 
   local -r template=$(cat <<EOF
 domain (ip ip6) table filter {
@@ -639,7 +664,7 @@ domain ({{ (ds "data").domain }}) table filter chain INPUT daddr {{ (ds "data").
 EOF
 )
 
-  echo "{ \"server\": ${server}, \"domain\": \"${domain}\", \"address\": \"${address}\", \"vpc_cidr\": \"${vpc_cidr}\", \"prefix_cidr\": \"${prefix_cidr}\" }" | jq '.' | gomplate \
+  echo "{ \"server\": ${server}, \"domain\": \"${domain}\", \"address\": \"${address}\", \"vpc_cidr\": \"${vpc_cidr}\" }" | jq '.' | gomplate \
     -i "${template}" -d data=stdin:///data.json > "${template_path}"
 
   chown root:root "${template_path}"
@@ -662,8 +687,34 @@ function get_owner_of_path {
   ls -ld "$path" | awk '{print $3}'
 }
 
+function trust-ca {
+  local -r source="${1}"
+  local name
+
+  name="$(basename "${source}")"
+
+  local -r path="/etc/pki/ca-trust/source/anchors/${name}"
+
+  cp -f "${source}" "${path}"
+  chown root:root "${path}"
+  chmod 644 "${path}"
+
+  update-ca-trust
+}
+
 function run {
   umask 027
+
+  if [[ ! -f "/etc/sysconfig/ec2-environment" ]]
+  then
+    log_error "/etc/sysconfig/ec2-environment: No such file"
+
+    exit 1
+  fi
+
+  set -o allexport
+  source "/etc/sysconfig/ec2-environment"
+  set +o allexport
 
   local server="false"
   local client="false"
@@ -673,9 +724,8 @@ function run {
   local systemd_stderr=""
   local bin_dir=""
   local user=""
-  local cluster_tag_key=""
-  local cluster_tag_value=""
-  local region=""
+  local auto_join_tag_key=""
+  local auto_join_tag_value=""
   local upgrade_version_tag=""
   local enable_gossip_encryption="false"
   local secrets_bucket_name=""
@@ -737,19 +787,14 @@ function run {
         user="$2"
         shift
         ;;
-      --cluster-tag-key)
+      --auto-join-tag-key)
         assert_not_empty "$key" "$2"
-        cluster_tag_key="$2"
+        auto_join_tag_key="$2"
         shift
         ;;
-      --cluster-tag-value)
+      --auto-join-tag-value)
         assert_not_empty "$key" "$2"
-        cluster_tag_value="$2"
-        shift
-        ;;
-      --region)
-        assert_not_empty "$key" "$2"
-        region="$2"
+        auto_join_tag_value="$2"
         shift
         ;;
       --autopilot-cleanup-dead-servers)
@@ -845,6 +890,12 @@ function run {
   assert_is_installed "aws"
   assert_is_installed "curl"
   assert_is_installed "jq"
+  assert_is_installed "gomplate"
+
+  if [[ "$enable_tls_encryption" == "true" ]]
+  then
+    assert_is_installed "update-ca-trust"
+  fi
 
   if [[ -z "$config_dir" ]]; then
     config_dir=$(cd "$SCRIPT_DIR/../config" && pwd)
@@ -862,10 +913,6 @@ function run {
 
   if [[ -z "$user" ]]; then
     user=$(get_owner_of_path "$config_dir")
-  fi
-
-  if [[ -z "$region" ]]; then
-    region="${EC2_INSTANCE_REGION}"
   fi
 
   local type
@@ -934,9 +981,8 @@ function run {
     generate_consul_config "$server" \
       "$config_dir" \
       "$user" \
-      "$cluster_tag_key" \
-      "$cluster_tag_value" \
-      "$region" \
+      "$auto_join_tag_key" \
+      "$auto_join_tag_value" \
       "$enable_gossip_encryption" \
       "$gossip_encryption_key" \
       "$enable_tls_encryption" \
@@ -972,6 +1018,8 @@ function run {
   generate_ferm_config "$server" \
     "$ipv6" \
     "$interface"
+
+  trust-ca "$consul_ca_file_path"
 
   start_consul "$server"
 }
